branches:
  only:
  - master
  - develop

services:
- docker

jdk:
  - openjdk8

env:
  global:
  - DOCKER_IMAGE=peregrinecms/peregrine-cms
  - DOCKER_USERNAME=gastongonzalez
  - secure: LcTg50vVUjZTQw34VpdpJsAlqT0J2qzMx7W8K+mgDgWP3qbg7jyw8hxGHu8p3U02wzWiluFbl5KJCYT1hJcPMeUTxUyS+6YW9Ws75ueGTTXVT6aMb4ElxBqup5hpUc2LIIcU+V4wkADBwUwPI4IOjieBe9cNE4TN0xYox4yjIZxPsQ/sbfKLKbnIw4q7v241ZDwKGT1j0lhOdAjYCdzTa2selsMe3uO/Hb1USt348MT5jitPKz9a2skXwVxUx5eMTycPHCautyh8qlMMpupPhFTmRnifplCxlN5rkDecl9Sf3DN9xxz3wktbTLuQ/hZngIH1uvA2AM6K1ztMwcRSOkDD06ypWDnK7qi3ae6egC5nCphqobzU/trzgadR9HthPVCStKKykFtNdOcsPHP4cee0ggLksVyAt3UZAMMpbJc3+B2LYvPD4eWKcIFvmK9omcuZhO2IbMpni3aR8V/WYT0JWQ7rK65Zf6O2ydyt9ti0AdQpRMM5ln5/AkruEnhIBdh5Q5SMpMKADqlJOBCq65HyXRKn1nSfXnk31/KQm6QoIsWNowM6AMBBLjLmz2vjQRpBQEcuiQkuwyYG1p42T0G7G62Cpt0WVKdM1O5QIhrGRy6JDduLfEtJYixTyQS/AJFcr8AejjRnecItLzdPmmGe50un5u85SG+vxdkaYaw=
  - secure: jfqjgE048K78zPc6ziRdb54P3cqsHKFuDmVODQ93X7ik3HpIm5wVql6iR7sjsPpmdLWMwr04Royb5pQWKemN2g0zw5n0PnI3VxKrD+51HvPEoLojmgTzTISCyQGexsQA7OlQdAmU+DwvNmqOZLUYv272XhkHmzM57ujYiGo5EUaWfz6C4icmesOd7sEg26LUNkCZie9GE9ngMyEWMjA5ol5lEIaU0JzYS4SSSO7f/2AHFOrjYasgfAwhafFUk99q2PBAPVoXbc+WLq2MiUbvQ9fbw9HWk3UvqQDKaEO0BTxepI3lG/A0crXDM5J/36ags/OLK6iKZfsrDqA4OcdjcU+l/tCIhroH4YilN1ry8ttAzjq7j0Ziu2oB+alF5qidZX7qdlLDeT3jYlcrJia1B7v932KToQ2HsHK3cnproyiEDVyJVVqZdlGUQ4NQQgP/+lppHjyA9J/EaiTw7S8xVwDESubThyjtpZQ/ujrzJizPcuQ1CN4uBiUCMqMZdNv9aQZwdyBEnuSLKyFXdZFe+Vfx/TrMB0I4ZbzOGATlhyI3Na9kftfJIEGi7t9xCZDp3Rk40T+kXj605qe1nQNfnICuiGgcX5QofUftbXB3/dKn6jfWC3ZRMhAK3axJmrLxSsNwwXzUu43GR4NWFwmXcp2iSP2lXsxvlYkkrEM2VWI=
  - secure: OcNzxZB7tGKilU80PELhlUEobCARyhJXG5QJOHiRP3C1ovlcCawd7gO+tSaGwTtnQf/x+Gm6HC3z8nfg8PcZc371V4Rv1bPdpn5DM7h8wRsGlWuLEYG4f/ZjWO5vuNBbwpEjXoMvXvX+V8lAcSVaNSvq1TxyCYzgpYLILgk2iCP/jXsQhxUV3jKhOj7lWmQpz/pX4hS8LSYeGkQw85uLfa5Qmwik8dOuSnua7KKRMvCtK69kTsMC3mgoMlWZ2M9i4elN+ScNPbLPa4lYtg99ern5pW9HGIlWV5kkJTFOId2UFjuZb5+X6QVNvxqH06AgzcD9c6FJAwERpART2QSexzi0Lr7BvBUtE4p5ncN3VrLzt0au59WpYUEyqUuDO1fOTziPrFHpUiN3z75OQIHpq9hMfwcku3Qdb8IfggRJCvyvULa1RAog70D+r2yhziVcJyD+du8/4YAfI6W/EOi3jDPWHbbdcbYiC/Uu1YRQal1AZPH/LrZePSpA0o2g2M9tjmLdfCdL1RXNoZIrhUanwtHcxEUvmCUyg8OjgUfODjA3MMZ3j4dw0+pqw9vTfHjB0owGNzdM2jXRSyUH86o5DIzKORQiL4x+iDA7CD0uE18D01TezhQtYsSiyR+UQckBPX60ZZxZFlRwIUW55M7HNl0hc75bft2qEg/biDMsLGY=
  - secure: OtzaxL//n/ALKtpxOCOm1UbB42IqGTexI/t93EpfP1CKDup1mYPD9alRDkximSRHrrwFqSF/R4wdmMQksYB0r8IQl8MTBnDWcY/tzsn0nFMlnCCV5QIzVXlM1kU6IirGscEDbdwxft4ure0lrDtzx9NuiQGWbv9+UZKgvWMJZdapLnDfMAtSCBBNxMlQk6j4d0RJncPDdbCMvSiP3XjT8YH93g05DyPWdikSn3KadBmv/evjqFC9h0qE7xUkuipyoRzV1LW1ngvdvrfrpqr5RaRMB4jPvYhZC9Wqqo/yw3jqIF/NWUEMLV+u0fs18bCMaay1EC8+KzqYGFhM6U67Fn4hJPSi5XzErQ901dr5huC0XiIKTekZu0qZ93vbDitr3zw7CGLE5Zfa7m501MrmsdFeOcI/AlYmKqOnrSvdZe3qXGVJkbOJP9kRlCWBnMExKGnUQtgffH9NR9ruuY6/fhbi1XmuDjxgk1tRPsl8usMt55g3jZWYwEsQSrAXLHuRbJBKetIAvXlNRDeVGAUS5ioEj+Pq32tnROTnP51FLWbwxHpS46qCyCt9pcFCKLisuSeBlkYa8vOEHPJqL6PfpGeBtx7akFuL1r/V3uqpz98shFGwx5YpmBDJ4DKMVO0msHfwY2pKBTXl+cfeGIM0kvQReYhIOswoRHjmmTYP0m8=
  matrix:
  - secure: x21cQdxtCEHV9BrGPmP+FzaraSoRbTAty2DDeNbycAjcJZsJt4hMcUy5tOBShCY2o/IlF6jVDHmDo3inRPbPQvhop9b4iK3vSfnzfk1cT+K2/TJw9r0ZtWS55A2nkxkG6QidJE03Oc557MY1ouJX5JTSoAm2FO5AQ+AOXorxtwSpBCGQTHGNOmRhV6CayerReaqoG8zEiVLin/uRf/vv0IqyW86vSe5mQWCRIK0V4Rjm1E8so9y/yjTxDU4KazTN6+Yu37m70pV3J42OcNr1nfF7tMjqu9RLUtxArDzmGPMKuAXYisq6tARkcB5MRZ1xVT0u25IFEKLyBYySbjMeD/fF3gra4yCnijnqGraYeXQ2IdPxf/5kcrtt85OMRG4OV3KDCrCOt64yX0t254UWccD1xN5nWm8ht61gAcpvZ8/yy/bD1MKeJvWBCpMYG5MblO33da78sMO0yY8ziSO0wO7fLx0b/0wspfz7dSlXo8FKKgj/+xKUnmi0ZWnhxwvi5fhvJIBANwmdE5Tmcy+OtgbhRoMfNHIQv3Bwqdolpp9Z8ROQxGnpUd4W4qUGz1UoO49DCwAEUz/j7E4zZKJyG4U+ZyHcFotN1KTCXkxR5O/d2Nej1jAL0fQWzuk2pAGsBkQAAbvcHtJIkmK5hCxXm3wVK9S/Cii68zfIb8QUudI=
before_install:
- echo $CI_GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $CI_GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
before_script:
- branch="$(echo ${TRAVIS_BRANCH} | tr '/' '-' | tr '[:upper:]' '[:lower:]')"
- version="$(awk '$2 == "APP_VERSION" { print $3; exit }' docker/Dockerfile)"
- tag="${branch}-${version}"

script:
- cd docker && ./builddocker.sh deploy

after_script:
- docker images

before_deploy:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker tag "$DOCKER_IMAGE" "${DOCKER_IMAGE}:latest"
- docker tag "$DOCKER_IMAGE" "${DOCKER_IMAGE}:${branch}"
- docker tag "$DOCKER_IMAGE" "${DOCKER_IMAGE}:${tag}"

deploy:
  # Stable release
  provider: script
  script: docker push ${DOCKER_IMAGE}:${tag}
  on:
    branch: master
  # Development release
  provider: script
  script: docker push ${DOCKER_IMAGE}:${branch} && docker push ${DOCKER_IMAGE}:latest
  on:
    branch: develop
